version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-test
    command: --init-file /data/database-init.sql
    volumes:
      - ./database-init.sql:/data/database-init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
  rest-api:
    image: rest-api:latest
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      PROFILE: dev
      DATABASE_URL: jdbc:mysql://mysql:3306/tedtalk
      DATABASE_USERNAME: tedtalk
      DATABASE_PASSWORD: 123456
